In [5]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\Namratha R\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [4]:
import numpy as np


# Exercise 1: Create Arrays
# 1. Create a 1D NumPy array containing the numbers 1 through 20.


In [6]:
# 1. Create a 1D NumPy array containing the numbers 1 through 20.
array_1 = np.arange(1, 20)
print("1D Array from 1 to 19:", array_1)

1D Array from 1 to 19: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


2.Reshape the array into a 4*5 matrix

In [26]:
# 2. Reshape a 1D array of size 20 into a 4x5 matrix.
array_11=np.arange(1, 21)
print(array_11)
reshaped_array = array_11.reshape(4, 5)
print("Reshaped 4x5 Array:\n", reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Reshaped 4x5 Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


3.Finding of MEAN,MEDIAN,MODE

In [28]:


# 3. Find mean, median, and standard deviation
mean_val = np.mean(array_1)
median_val = np.median(array_1)
std_val = np.std(array_1)

print("\nMean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)





Mean: 10.0
Median: 10.0
Standard Deviation: 5.477225575051661


4.Extract all even Numbers from the array

In [33]:
# 4. Extract all even numbers
even_numbers = array_11[array_11 % 2 == 0]
print("\nEven Numbers:\n", even_numbers)



Even Numbers:
 [ 2  4  6  8 10 12 14 16 18 20]


5.Generate a Random 5*5 matrix 
-Transpose of Random Matrix

In [34]:
# 5. Generate a random 5x5 matrix and compute its transpose
random_matrix = np.random.rand(5, 5)
transpose_matrix = random_matrix.T

print("\nRandom 5x5 Matrix:\n", random_matrix)
print("\nTranspose of Random Matrix:\n", transpose_matrix)









Random 5x5 Matrix:
 [[0.74915829 0.71837711 0.09181715 0.54501241 0.62913801]
 [0.13536094 0.80784096 0.73474126 0.04760553 0.20136239]
 [0.08270088 0.15625265 0.38853094 0.80160248 0.0947574 ]
 [0.21958215 0.11456443 0.99095971 0.16842802 0.24615994]
 [0.30266734 0.79888171 0.678933   0.41558414 0.93435726]]

Transpose of Random Matrix:
 [[0.74915829 0.13536094 0.08270088 0.21958215 0.30266734]
 [0.71837711 0.80784096 0.15625265 0.11456443 0.79888171]
 [0.09181715 0.73474126 0.38853094 0.99095971 0.678933  ]
 [0.54501241 0.04760553 0.80160248 0.16842802 0.41558414]
 [0.62913801 0.20136239 0.0947574  0.24615994 0.93435726]]
