In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 26.0
[notice] To update, run: C:\Users\Namratha R\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
#Exercise 1 Create Arrays

In [3]:
# 1. Create a 1D NumPy array containing the numbers 1 through 10.
array_1 = np.arange(1, 10)
print("1D Array from 1 to 09:", array_1)

1D Array from 1 to 09: [1 2 3 4 5 6 7 8 9]


In [5]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [12]:
# 2. Create a 3x3 matrix of zeros.
matrix_zeros = np.zeros((4, 4))
print("3x3 Matrix of Zeros:\n", matrix_zeros)

3x3 Matrix of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
# 3. Create a 2x3 matrix filled with ones.
matrix_ones = np.ones((2, 4))
print("2x3 Matrix of Ones:\n", matrix_ones)

2x3 Matrix of Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
# 4. Create an array of numbers from 0 to 25, with a step of 3.
array_step = np.arange(0, 22, 3)
print("Array from 0 to 20 with step 2:", array_step)


Array from 0 to 20 with step 2: [ 0  3  6  9 12 15 18 21]


In [17]:
# 5. Create a 4x4 identity matrix.
identity_matrix = np.eye(4)
print("4*4 Identity Matrix:\n", identity_matrix)

4*4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
Exercise:2 Array Operations


In [4]:
# 1. Create two arrays, `a` and `b`, of size 3. Perform element-wise addition, subtraction, multiplication, and division.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a)
print(b)
addition = a + b
subtraction = a - b
multiplication = a * b
division = a / b
print("Element-wise Addition:", addition)
print("Element-wise Subtraction:", subtraction)
print("Element-wise Multiplication:", multiplication)
print("Element-wise Division:", division)

[1 2 3]
[4 5 6]
Element-wise Addition: [5 7 9]
Element-wise Subtraction: [-3 -3 -3]
Element-wise Multiplication: [ 4 10 18]
Element-wise Division: [0.25 0.4  0.5 ]


In [ ]:
# 2. Find the maximum and minimum values in a 2D array.
array_2d = np.array([[2, 5, 8], [6, 8, 3], [8, 4, 9]])
max_value = np.max(array_2d)
min_value = np.min(array_2d)
print("Max Value:", max_value)
print("Min Value:", min_value)


Max Value: 9
Min Value: 1


In [6]:
# 3. Compute the sum of all elements in a 2D array along the rows and columns.
print(array_2d)
sum_rows = np.sum(array_2d, axis=1)
sum_columns = np.sum(array_2d, axis=0)
print("Sum along rows:", sum_rows)
print("Sum along columns:", sum_columns)

[[3 1 4]
 [5 9 2]
 [6 8 7]]
Sum along rows: [ 8 16 21]
Sum along columns: [14 18 13]


In [7]:
# 4. Find the mean, median, and standard deviation of a given 1D array.
array_1d = np.array([1, 2, 3, 4, 5])
mean_val = np.mean(array_1d)
median_val = np.median(array_1d)
std_dev_val = np.std(array_1d)
print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_dev_val)

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


In [ ]:
Exercise:3 INDEXING & SLICING

In [9]:
print(array_1)
array_pos = array_1[-2]
print(array_pos)

[1 2 3 4 5 6 7 8 9]
8


In [10]:
# 1. Create an array of size 10 and access the 5th element.
array_10 = np.arange(1, 11)
print(array_10)
fifth_element = array_10[6]
print("5th Element:", fifth_element)


[ 1  2  3  4  5  6  7  8  9 10]
5th Element: 7


In [11]:

# 2. Slice a 2D array to get all rows except the first and all columns except the last.
array_2d = np.array([[3, 1, 4], [5, 9, 2], [6, 8, 7]])
print(array_2d)
print('---------------------------')
sliced_array = array_2d[1:, :-1]
print("Sliced Array:\n", sliced_array)
print('---------------------------')

print(array_10)
split = array_10[4:-1]
print(split)

[[3 1 4]
 [5 9 2]
 [6 8 7]]
---------------------------
Sliced Array:
 [[5 9]
 [6 8]]
---------------------------
[ 1  2  3  4  5  6  7  8  9 10]
[5 6 7 8 9]


In [12]:
# 3. Use boolean indexing to create a new array with only even numbers from an existing array.
print(array_10)
even_array = array_10[array_10 % 3 == 0]
print("Even Numbers Array:", even_array)


[ 1  2  3  4  5  6  7  8  9 10]
Even Numbers Array: [3 6 9]


In [13]:
# 4. Reshape a 1D array of size 9 into a 3x3 matrix.
array_11=np.arange(1, 17)
print(array_11)
reshaped_array = array_11.reshape(4, 4)
print("Reshaped 3x3 Array:\n", reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Reshaped 3x3 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
EXERCISE:RANDOM NUMBERS

In [14]:
# 1. Generate a 1D array of 10 random integers between 1 and 100.
random_integers = np.random.randint(1, 101, size=15)
print("Random Integers Array:", random_integers)


Random Integers Array: [69 92 64 56 96 42 42 24 71 36 81 26 85  6 64]


In [15]:
# 2. Create a 3x3 matrix of random numbers from a normal distribution.
random_normal = np.random.randn(3, 3)
print("3x3 Random Normal Distribution Matrix:\n", random_normal)


3x3 Random Normal Distribution Matrix:
 [[ 1.78309471  0.57425906 -0.43222656]
 [-1.18542833 -0.56155783  0.88896304]
 [-0.71052159  0.75341049 -2.29781722]]


In [16]:
# 3. Generate a 2D array of random integers between 0 and 10, and then sort it along each row.
random_ints = np.random.randint(0, 21, size=(2, 3))
print(random_ints)
sorted_random_ints = np.sort(random_ints, axis=1)
print("Sorted Random Integers along rows:\n", sorted_random_ints)


[[ 7  1 12]
 [19 18 19]]
Sorted Random Integers along rows:
 [[ 1  7 12]
 [18 19 19]]


In [ ]:
EXERCISE:5 ARRAY CONCATENATION

In [17]:
# 1. Concatenate two 1D arrays horizontally and vertically.
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])
concat_horizontal = np.concatenate([array_1, array_2])
concat_vertical = np.concatenate([array_1.reshape(3, 1), array_2.reshape(3, 1)], axis=1)
print("Horizontally Concatenated Array:", concat_horizontal)
print("Vertically Concatenated Array:\n", concat_vertical)


Horizontally Concatenated Array: [1 2 3 4 5 6]
Vertically Concatenated Array:
 [[1 4]
 [2 5]
 [3 6]]


In [18]:
# 2. Stack two 2D arrays vertically and horizontally.
array_2d_1 = np.array([[1, 2], [3, 4]])
array_2d_2 = np.array([[5, 6], [7, 8]])
stack_vertical = np.vstack([array_2d_1, array_2d_2])
stack_horizontal = np.hstack([array_2d_1, array_2d_2])
print("Vertically Stacked Array:\n", stack_vertical)
print("Horizontally Stacked Array:\n", stack_horizontal)


Vertically Stacked Array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontally Stacked Array:
 [[1 2 5 6]
 [3 4 7 8]]


In [19]:
# 3. Split a 1D array into three equal parts.
split_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
split_parts = np.split(split_array, 3)
print("Split Array into 3 parts:", split_parts)

Split Array into 3 parts: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [ ]:
EXERCISE:LINEAR ALGEBRA

In [20]:
# 1. Calculate the dot product of two 1D arrays.
a = np.array([1, 2])
b = np.array([3, 4])
dot_product = np.dot(a, b)
print("Dot Product:", dot_product)


Dot Product: 11


In [21]:

# 2. Solve a system of linear equations using np.linalg.solve()
A = np.array([[3, 1], [1, 2]])
B = np.array([9, 8])
solution = np.linalg.solve(A, B)
print("Solution of linear equations:", solution)

Solution of linear equations: [2. 3.]
